sudo: false
language: node_js
node_js:
- '0.12'
before_script:
- npm install -g bower grunt-cli
- bower install
- gem update --system
- gem install compass
- "./authGithubTsd.sh"
env:
  global:
    secure: CBTF63d2JgD0dpWt/Oj5y5AMXApN98kmVpNoREuJnhobZag36EBGHC8G+OMD4fC89wckbQ52oxVejyLnKFk4f5AGXdBXfqarjN+cdBH4tJDVshTXRUd7tTyVzOsE/bhYENzVYxjVH3+kiB99c4Mqf5BODwFcOoVFNaHwYQlV+2NAKmWotZq78dBqpCMGoxiClsdwLZ3inUb8TtccRDW08PD5T2LAe6u9qPz2WakIdqwp2njOhjqIKurTIf91Lz1xWQK+VvP4LysIZ7Ai8L5MgHYDYGwVHaWi6tlLGLPGMOsiWsp9X7KKUdahtcmJmGZHWWvuZ0lKrk7RX/tuaBKKGo7thO3PMbmK7/dL3nCdt6gdAHBCFfopPT1gYPG/gtxV9Z78C4xIw1QyTcE9gMPEPMElbPdHJjf76Y/0Sf1M9/KH77MzUvR29kRR0IivysqlN6TB/jwHgf6/sPV+hm1kwAPgoeGwEW9vFN2Qix6jpGsimjtKukziSguV0JnO7ASp5mdUakhZP1zS1wjYoIwjvTgFdfgmuDMvxe+NGmozA3o1H4ErwEw4ihQxdJn4UC4FcyfiNA3W2CqYkASAbferIpIt0mf1tVjGc+GoQyedkctW3JrRbjxOMyZJxyAvGbwgwvWx/F2hE6JMMlu31vFDJ1TNSALonzhsr7BDh9BLIOo=
